### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ghost** [pgrimaud/priceminister-sdk#1]
Hi everybody,

Can you tell me how I can use your bundle, I did : composer require pgrimaud/priceminister-sdk
But after wrote my login and password in my controller, I have the error : 

> Attempted to load class "PriceministerClient" from namespace "AppBundle\Controller\Priceminister".
> Did you forget a "use" statement for "Priceminister\PriceministerClient"?

What do I to add in AppKernel.php and my controller ?

Sorry but I'm a beginner...
Have a nice day.

Symfony 3.4

**Comment by pgrimaud** [comment]
Hi,
No, you don't have to add something in your `AppKernel.php`.

If you're in a Symfony 3.4 bundle, you should try this : 

```php
<?php

namespace AppBundle\Controller;

use Priceminister\PriceministerClient;
use Priceminister\ProductListing;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class PriceministerController extends Controller
{
    /**
     * @Route("/", name="homepage")
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        $client = new PriceministerClient('yourLogin', 'yourToken');

        $productListing = new ProductListing($client);
        $productListing->setParameter('kw', 'iron man tome 1 croire');
        $result = $productListing->request();

        dump($result);

        //return $this->render('BackBundle:Home:home.html.twig');
    }
}

```

Just add the the following `use`
```php
use Priceminister\PriceministerClient;
use Priceminister\ProductListing;
```
And when you're working with this library in a SF3 environment, remove the prefix ` Priceminister\`

Hope it helps you.

**Comment by ghost** [comment]
Thank you !

There is a small mistake (maybe it's me), when I do:
`print_r($result->getProducts());`

I have:
`Array ( [0] => Array ( [id] => 283617873 [values] => Array ( [name] => Iron Man Tome 1 - Croire [image] => https://pmcdn.priceminister.com/photo/984727643_ML.jpg [breadcrumb] => Livres > BD et humour > Comics [caption] => [topic] => Livre [offers] => 14 [bestprice] => 4 [url] => https://fr.shopping.rakuten.com/offer/buy/283617873/iron-man-marvel-now-tome-1-de-greg-land.html [barcode] => 9782809436303 ) ) ) `

Bestprice has 4, but when I try:
`print_r($result->getBestPrice(false));`

I have 9.29
But at the moment, thank you so much!!

**Comment by pgrimaud** [comment]
Yeah, with a boolean parameter (`true` or `false`) into the method `getBestPrice()`, you can retrieve item with the best price, with or without shipping cost. For example : 

```php
// get price with shipping cost
echo $result->getBestPrice();
=> 9.29

// get price without shipping cost
echo $result->getBestPrice(false);
=> 4
```
The offer for your product (4.00€ for the book + 5.29€ for the shipping cost) : 

![image](https://user-images.githubusercontent.com/1866496/45720741-a2323f00-bba5-11e8-9d9b-3c388480b72e.png)

**Comment by ghost** [comment]
Yes yes, I had understand but I would like to keep the price without shipping cost, but when I tries with
`echo $result->getBestPrice(false);`

I have not 4 as price, but 9.29.

Problem resolved, I had used the fonction: getBestPriceWithoutShippingCost()
And I have 4 :)

Once again, thank you so much for your answer and the work 🥇
